name: Spinark
favicon: null
layout_spectrum: 0.26459
typography_spectrum: 0.51459
title: spinark
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94ba33'
  brandStrength: 0.9942543846555054
  lightness: 0.6875
  saturation: 0.9334656388964504
  rhythmicContrast: 0.061563525116071105
purpose: []
