name: Spinark Telecom
favicon: null
layout_spectrum: 0.26459
typography_spectrum: 0.49125
title: 'spinark telecom & software'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#94ba33'
    - '#414143'
    - '#b6b6b6'
    - '#929292'
  brandStrength: 0.9942543846555054
  lightness: 1
  saturation: 0.9334656388964504
  rhythmicContrast: 0.061563525116071105
purpose: []
